<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>cheatsheet</string>
    </array>

    <key>name</key>
    <string>cheatsheet</string>

    <key>scopeName</key>
    <string>source.cheat-sheet</string>

    <key>patterns</key>
    <array>
      <!-- Headings -->
      <dict>
        <key>match</key>
        <string>^#-#.*$</string>
        <key>name</key>
        <string>comment</string>
      </dict>
      <!-- Comments -->
      <dict>
        <key>match</key>
        <string># .*</string>
        <key>name</key>
        <string>comment</string>
      </dict>
      <!-- Box drawing -->
      <dict>
        <key>match</key>
        <string>[│─└┌┐┘┬┼┴]</string>
        <key>name</key>
        <string>comment</string>
      </dict>
      <!-- Arrow comments -->
      <dict>
        <key>match</key>
        <string>.*[└┌┐┘─].*</string>
        <key>name</key>
        <string>comment</string>
      </dict>
    </array>
  </dict>
</plist>
